### ISSUE TITLE
Issue: only downlaods part of the music

### ISSUE THREAD

**Issue by GGamer2042** [Footsiefat/zspotify#187]
sometimes when downloading an album, some songs dont fully download, for example one of the songs is 1:50 min long but it downloads only 24 seconds, although I am running version 0.2.4 and not 0.2.4.1, ill see if its fixed on the new version, also im using the python source code and not the prebuilt, python source code is superior because of zs_config and just convenience of not being in %temp%

**Comment by GGamer2042** [comment]
WHAT THE FUCK DID U DO WITH 2.4.1
IT NEEDS SOME CONFUSING - COMMAND LINE OPTION
JUST LET ME DO "PY ZSPOTIFY"
THEN INTPUT MY USER AND PASS
AND INTPUT LINK

**Comment by logykk** [comment]
Next time just read the one line of output ```one of the arguments urls -ls/--liked-songs -p/--playlist -s/--search is required```. It says right there you just need to add a single extra `-s` to get the search.

**Comment by RobertSchneider2** [comment]
> 
> 
> sometimes when downloading an album, some songs dont fully download, for example one of the songs is 1:50 min long but it downloads only 24 seconds, although I am running version 0.2.4 and not 0.2.4.1, ill see if its fixed on the new version, also im using the python source code and not the prebuilt, python source code is superior because of zs_config and just convenience of not being in %temp%

I can second that many almost all longer playlists and albums contain interrupted songs. Example: 

https://open.spotify.com/album/6BND642AFiY7f5YIiEYVQa?si=quO1YLHlR3Szq-11ptiLnw

The second song from the album downloads only 44 seconds instead of 4:48 when downloading the album.

However, downloading the song via the direct track link https://open.spotify.com/track/4vS8PHPhsvEm0TbforJtOk?si=bf91140020d7400c will give a correct download.

The issue can be replicated. 
Confirmed on 0.2.4 and not 0.2.4.1 pre build

**Comment by GGamer2042** [comment]
alright on 2.4.1 it seems to be fixed, or maybe i got lucky
anyways the -s was confusing because I thought it searched with the name at
first and i wanted to download with the link

**Comment by logykk** [comment]
Should now be fixed in the latest windows build too.
