### ISSUE TITLE
[BUG] part of audio missing from file

### ISSUE THREAD

**Issue by CrimsonFez** [Footsiefat/zspotify#34]
i found a weird bug. 3 seconds are missing from the middle of a song. hasn't happened with any other song, and keeps happening with this specific song every time i download it. 
https://open.spotify.com/track/2Ke4N9DMxzlEaiXMhlUlUm?si=7fa2b9c18a294a97 
the missing part is at 0:49. the song is supposed to be 4:36 in length, when downloaded its 4:33
i've played it on vlc and gnome-music, both have this issue

**Comment by Footsiefat** [comment]
![image](https://user-images.githubusercontent.com/12180913/138188196-fe0458c1-97fe-4182-93a6-73c6a6c785b9.png)
Odd im not having that issue, although I dont have a premium account to test with tho.

SOrry guys I litterally cannot fix this since I dont have a premium account to debug :/

gonna have to close this @xRuffKez @MKetonen @bravexd @CrimsonFez
